name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-test:
    name: Build & Test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --group dev --group test

      - name: Lint with ruff
        run: |
          uv run ruff check src/ tests/

      - name: Type check with pyright
        run: |
          uv run pyright src/ tests/

      - name: Run tests with pytest
        run: |
          uv run pytest --maxfail=2 --disable-warnings --tb=short

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: .pytest_cache/

  publish:
    name: Publish to PyPI
    runs-on: macos-latest
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
